### ISSUE TITLE
[PC] - Keine Aktualisierung nach dem hinzufügen von Liedern / Ordnern

### ISSUE THREAD

**Issue by ewertmaster** [we-kode/mml.project#2]
**Describe the bug**
Nach dem Hinzufügen von Ordnern, wird die Ansicht nicht richtig aktualisiert. Erst nach einem Verlassen der Ansicht und wieder reingehen wird die komplette Liste angezeigt.

**To Reproduce**

**Expected behavior**
Aktualisierung sollt automatisch durchgeführt werden oder alternativ ein Aktualisierungs Button hinzufügen.

**Screenshots**

**Desktop (please complete the following information):**
 Desktop APP - Version ? (wird auch nicht dargestellt.)

**Additional context**

**Comment by stummk** [comment]
- [x] Add posibility to update the records view in the admin app without changing screen
