### ISSUE TITLE
[APP & PC] - Gruppierung und verwaltung nach Jahren / Monaten / Tagen

### ISSUE THREAD

**Issue by ewertmaster** [we-kode/mml.project#3]
Eine mögliche Anzeige der Titel gruppiert nach Jahren, Monaten oder Tagen.
In der PC-APP dazu auch die Auswahlmöglichkeit ganze Jahre / Monate / Tage zu löschen.

**Comment by stummk** [comment]
- [x] Add grouping settings to app (flat or hirarchical)
- [x] Add grouping settings to administration app (flat or hierarchical)
- [x] Removing reecords in administration app hierarchical
